name bucklespring
menu - b Bucklespring
icon - #{@buckle_icon_color}
daemon %CACHE%/tmux-bucklespring/buckle.pid buckle
cache %CACHE%/tmux-bucklespring
persist @buckle_enabled
persist @buckle_gain
persist @buckle_profile
persist @buckle_quiet_from
persist @buckle_quiet_to
volatile @buckle_icon_color
volatile @buckle_perm_error
attach attach
restore restore
lint plugin.sh
